### PR TITLE
ref. #152 improve create-component after monorepo

### PR DESCRIPTION
**Pull request by lorenaramonda**
# Related issue
#152

# Scope of work
I fixed the path where the scss must be created. The script was already into packages/vue and must run from here to use it.

# Screenshots of visual changes

# Checklist

- [x] I followed [composition rules](https://github.com/DivanteLtd/storefront-ui/blob/master/docs/component-rules.md) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by lorenaramonda** [comment]
Hi @filrak and @leomp12 did you plan to have a create-component one per type of repo (vue, react, angular, whatever) **inside** their own folder or would you consider to have one **root** create-component to manage them all?

lord-of-the-rings-ring-1

**Comment by filrak** [comment]
Imho one per repo. It's too specific to have a general script. Also right now we are forcing people to cd into specific project and run commands from there. I'm not sure if it's the best approach but for sure it's safe. I'm open to discussion tho

**Comment by lorenaramonda** [comment]
@filrak it also depends on how the other frameworks components will look like, for instance, have you already thought about how the react component (and repo) will look like as files structure?
will it follow the vue files structure and it will be necessarily different?

**Comment by filrak** [comment]
When I gave it a second thought @lorenaramonda your idea seems to be better. Probably we should have a template folder in every framework-specific repo. In template folder we will have all files required by CLI with a special strings that will be replaced by vars passed by CLI. This will make things more elegant and easier. WDYT?

Below examples of such string-based templates

```js
// SfComponent.spec.ts
import { #{ComponentNameCamelCase} } from "@/components/#{ComponentType}/#{ComponentNameCamelCase}.vue"

decribe("#{ComponentNameCamelCase}.vue", () => { ...
});
```

Then during files creation we can easily replace let's say `#{ComponentNameCamelCase}` just by using `string.repalce()` on a files content.

WDYT?

**Comment by leomp12** [comment]
@lorenaramonda I also prefer the way you implemented it, with just one root script.
One per type of repo would create repeated code, which is bad.
And @filrak idea sounds good to me, one template folder for each type of repo, then the `create-component` script should read those files for the respective chosen type :)

**Comment by lorenaramonda** [comment]
yes, also I do think this could fit. I'm gonna implementing it 👍 stay tuned 😉

**Comment by filrak** [comment]
Thanks! 
You're awesome!

**Comment by lorenaramonda** [comment]
Hi @filrak 
i think i will probably only use `ComponentNameCamelCase` and `ComponentNameKebabCase` instead of your proposal `#{ComponentNameCamelCase}` and replace those because not in every row will work as it's not a "normal" string, but I think that these two conventional names could work

**Comment by lorenaramonda** [comment]
Hi @filrak I pushed the changes, let me know if it's ok now 😉

**Comment by filrak** [comment]
@lorenaramonda sure, feel free to use it like this. It's just easier to spot places that are meant to be repalced if you wrap the text with special chars but it's subjective so I'm not tied to it

**Comment by filrak** [comment]
Thanks! 
image

**Pull request merged**
