### PR TITLE
add Button README.md

### PR DESCRIPTION
**Pull request by decadef20**
# Scope of work
rename CSS variable and add readme.md

# Checklist

- [x] I followed [composition rules](https://github.com/DivanteLtd/storefront-ui/blob/master/docs/component-rules.md) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by filrak** [comment]
Hey, the convention with SCSS vars is actually to nto have a prefix (nothing I'm tied to but this is just how it looks on other compoennts).

**Comment by decadef20** [comment]
> Hey, the convention with SCSS vars is actually to not have a prefix (nothing I'm tied to but this is just how it looks on other compoennts).
> 
> Btw thanks for contributing man ;) could you ping me on VS slack? I want to know you better ;)

Thanks for correcting me.  
I think SCSS vars name rules should be told in the doc.
There are still some works to rename SCSS vars with a prefix.
I sent you a message on slack

**Comment by filrak** [comment]
Thanks!

**Comment by filrak** [comment]
@lauragift21 could you remember about this part in docs?

**Comment by lauragift21** [comment]
Sure noted @filrak

**Pull request merged**
