### PR TITLE
proposal for git flow

### PR DESCRIPTION
**Pull request by lorenaramonda**
# Related issue

None

# Scope of work

Define the proper flow using gitflow to work on feature and create releases. Follows discussion.

# Checklist

- [x] I followed [composition rules](https://github.com/DivanteLtd/storefront-ui/blob/master/docs/component-rules.md) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by lorenaramonda** [comment]
Also, @filrak I do think that until there is not a real production version (that should stay under 1.0.0 as the first one) the beta releases (or at least the first) should stay under 0.x.x until bug free and ready for production, IMHO

**Comment by lorenaramonda** [comment]
@leomp12 but what about the hotfix process through PRs?

**Comment by leomp12** [comment]
@lorenaramonda what do you mean by "hotfix process through PRs"?

I agreed with your purpose to use a develop branch and leave master for stable, and I think you explained it well in `CONTRIBUTING.md` in this PR.
Also agree with your comment about v1 release.

**Comment by lorenaramonda** [comment]
sorry @leomp12 I refer to the comment I left on the line 23 on the commit that you can also find upper scrolling up this page:

> also, the hotfix in a normal gitlow repo, starts from master and when closed it merges straight to master AND develop so it's named with the next release number upgrading the last number in this way: x.x.1, x.x.2, etc.. therefore, as it finish to master without passing through a release branch, all the release branch's operation must be perfomed before closing, such as updating the changelog.

**Comment by filrak** [comment]
@lorenaramonda yes, I totally agree about versioning.

Regarding hotfixes I think they should be proposed directly to master.

Also I guess before beta release we can safely use master as develop branch. WDYT?

**Comment by lorenaramonda** [comment]
Yes @filip I think that until beta it perfectly works fine to work on master only 👍

**Comment by filrak** [comment]
Could you please add this information to docs too?

**Comment by filrak** [comment]
@lorenaramonda ? ;)

**Pull request closed without merging**
