### PR TITLE
Render the HTML of the description

### PR DESCRIPTION
**Pull request by rozzilla**
Instead of rendering the raw code of the description, add a v-html to render the HTML code.

# Related issue

Closes #

# Scope of work

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented 

If applicable:

- [x] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
@rozzilla Hi, is this change necessary for some reason? We usually try to avoid using v-html.

**Comment by rozzilla** [comment]
Hi @AdamPawlinski , yes. This is needed since I think it happens many times to have HTML code inside the description. Now, if it happens in this case, you see just the raw code, instead of the rendered one.

**Comment by rozzilla** [comment]
For example, in a project we're working on, the product descriptions contain HTML tags. So we need to render those...

**Comment by AdamPawlinski** [comment]
@rozzilla What do you think about using slot here:
```
<template #description> 
   <p v-html="description"> 
   </p>
</template>
```
Also I wonder if using <p> element is good in this case, because not every element can be nested in it.

**Comment by rozzilla** [comment]
I confirm @AdamPawlinski it works greatly. Sorry for my PR so, I didn't check it before...

**Pull request closed without merging**
