### PR TITLE
hotfix:  checkbox without error msg

### LINKED ISSUE #1352: [BUG] Checkbox doesn't have error message.
**Describe the bug**
A checkbox has only valid property, but e.g. in form user may don't know if that checkbox may be required

**How to reproduce**
1. Go to form with a required checkbox
2. Click on a send form button
3. Can't see error message.

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #1352 

# Scope of work
Error message slot has been added to checkbox

# Screenshots of visual changes
Zrzut ekranu z 2020-08-07 11-00-11

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by filrak** [comment]
@AdamPawlinski you'll have to add here your error msg component

**Comment by AdamPawlinski** [comment]
I fixed conflicts and add msg element similar to that in input and select, made some small fixes of css.

**Comment by AdamPawlinski** [comment]
My commits will be removed, because I merged develop to it, not seeing that this changes goes to master.

**Comment by AdamPawlinski** [comment]
I fixed this branch and it is ready to merge with new msg slot. New component https://github.com/DivanteLtd/storefront-ui/issues/1345 can be applied later.

**Comment by AdamPawlinski** [comment]
Add red border to checkbox in error state. In error state with required set to true  message has no red color. 
Also stories need to be fixed - only one of invalid/error-message should stay.

**Comment by AdamPawlinski** [comment]
Fixed styling and unnecessary story removed.

**Pull request merged**
