### PR TITLE
hotfix: MegaMenu confusing on theme

### LINKED ISSUE #1029: [BUG] MegaMenu confusing on theme
## Description
related: https://github.com/DivanteLtd/shopware-pwa/pull/593

During our first implementation, there is a problem with recognizing where megamenu is and where the template is. 

image

on Figma, there is a grey overlay with megamenu, so there is one more issue how to show properly more top-level categories without subcategories

## Acceptance criteria
- [ ] add overlay area to mega menu
- [ ] [DESIGNS] add instructions to what is the proper way to show an example from the screenshot and in case that only some of the categories contain subcategories (@mbaran-dvnt )
- [ ] Above example with a larger number of categories and still place for banners from Figma designs

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #1029 

# Scope of work
SfOverlay added in stories SfHeader

# Screenshots of visual changes
Zrzut ekranu z 2020-08-05 11-07-39

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
Well prepared, but I wonder is that story should be inside SfMegaMenu of should it be in SfHeader as the main component is header and MegaMenu is put inside. Wdyt @filrak ?

**Comment by AdamPawlinski** [comment]
Finally, I added overlay and banners to SfHeaderNavigation story and leave the story in MegaMenu.

**Comment by filrak** [comment]
Shouldnt that be a part of `SfHeaderNavigation` component as well?

**Comment by AdamPawlinski** [comment]
If you mean SfMegaMenu to be part of SfHeaderNavigation it can be added inside default slot.

**Pull request closed without merging**
