### PR TITLE
fix: SfColorPicker opacity affects SfColor

### LINKED ISSUE #1497: [BUG] SfColorPicker opacity affects SfColor
**Describe the bug**
There is opacity in SfColorPicker that affects opacity also in SfColor. On our designs, colors don't have opacity and it should be fixed.

**How to reproduce**
1. Add SfColorPicker to SfProductCard
2. Change on mobile view
3. Open SfColorPicker

**Expected behavior**
SfColor in SfColorPicker doesn't have opacity 
Zrzut ekranu z 2020-10-26 09-51-48

**Actual behavior**
SfColor in SfColorPicker has opacity

Zrzut ekranu z 2020-10-26 09-52-47

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #1497 

# Scope of work
Removed opacity that affected SfColor and SfOverlay added

# Screenshots of visual changes
No visual changes 

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
@justyna-13 What do you think about leaving 0.8 opacity for colorpicker and change it to 1 only for color? I think that is on this design https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-%7C-Design-System?node-id=4731%3A15049

**Comment by justyna-13** [comment]
@AdamPawlinski it is exactly as you say it :) there is opacity 0.8 for SfColorPicker and it doesn't affect SfColor so that it has opacity 1 :)

**Comment by justyna-13** [comment]
You can see it on this example with background :)
Zrzut ekranu z 2020-10-30 13-58-40

**Comment by AdamPawlinski** [comment]
You are right :) I'm sorry I didn't test it properly

**Review by AdamPawlinski — APPROVED** [review]
It's great :)

**Pull request merged**
