### PR TITLE
fix: SfCheckbox cursor on checkbox input behaviour fixed

### LINKED ISSUE #1142: [BUG] Cursor inconsistency in SfCheckbox
_Let's take a journey to the beautiful land of Storefront UI Storybook. 
Today we want to visit the Category Page story: https://storybook.storefrontui.io/?path=/story/pages-category--common
Such a beauty... isn't it? But... oh noes! It's got a scratch!_ 😱

**Describe the bug**

The scratch is hidden in the filters sidebar. 
When you move your cursor over one of the first select boxes you can see some part of the area causes that the cursor changes to the default one and you lose highlight of the box.
It's because the input has got bigger recently (before it was 1x1 px _somewhere over the rainbow_).
Moreover, if you scroll to some next filters, you no longer see this effect - it's because the input has absolute position, thus it's stuck somewhere _far far away_, below the visible part of the document. 

**Expected behavior**

Well, the cursor on whole checkbox should remain consistent. 🙂

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue
Closes #1142

# Scope of work
set 1px for width and height, move native radio and checkbox input out of page

# Checklist

- [x] No commented blocks of code left
- [ ] Run tests and docs
- [x] Self code-reviewed

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
I added z-index to hide input but I am not sure if it is good solution, so please take a look.

**Comment by martaradziszewska** [comment]
@AdamPawlinski how about give the input `cursor: pointer` ?  `z-index` can mess the position of the other elements on the page.

**Comment by pspaczek** [comment]
@AdamPawlinski @martaradziszewska  IMO the best way is adding for input 1p for width and height. @AdamPawlinski please check SfRadio too. You can add `position: relative` for &__container and test is everything working OK

**Comment by AdamPawlinski** [comment]
inoput changed to 1px and moved outside. SfRadio also fixed

**Pull request merged**
