### PR TITLE
Update all svg icons as icons list, update SfIcon to accept mutiple paths and predefined icon name

### PR DESCRIPTION
**Pull request by mayashavin**
# Related issue
https://github.com/DivanteLtd/storefront-ui/issues/155

# Scope of work
1. Update all icons which were served as `img` to use SfIcon
2. Convert all SVG icons paths in assets to JS file with only path as string, as `icons.js` in `public/assets`
3. Create set of pre-defined icons.
4. Allow `SfIcon` to accept multiple SVG paths (`array`), a path (`string`) or pre-defined icon name (from icons list, as `string`).
5. Allow `SfIcon` to accept `viewBox` in case the paths are designed according to a specific viewBox size other than our default `0 0 24 24`. This is only relevant to customized paths.
6. Rename icons files and remove all the duplicate icons.

# Screenshots of visual changes
Screen Shot 2019-06-28 at 1 36 13

# Checklist

- [x] I followed [composition rules](https://github.com/DivanteLtd/storefront-ui/blob/master/docs/component-rules.md) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by filrak** [comment]
@mayashavin Maybe we also should make more descriptive names for icons?

**Comment by filrak** [comment]
Btw stunning work, you're awesome!

**Comment by mayashavin** [comment]
@filrak Thanks :) Let's discuss about the naming of icons :)

**Comment by mayashavin** [comment]
@filrak please continue reviewing

**Pull request merged**
