### PR TITLE
#167 Implement SfFooter (Work in Progress)

### PR DESCRIPTION
**Pull request by Flyingmana**
# Related issue
#167 

# Scope of work
Create a new molecule for the Footer
* Desktop design needs a bit finetuning
* Mobile design still missing

# Screenshots of visual changes
image

# Checklist

- [ ] I followed [composition rules](https://docs.storefrontui.io/component-rules.html) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by przspa** [comment]
how you doin @Flyingmana do you need some help on this issue 😃

**Comment by Flyingmana** [comment]
@przspa actually yes.
My initial plan for mobile was to use the existing Accordion element. But it seems its not recommended, to duplicate the content of <slot>, and its also not trivial.
Do I need to reimplement parts of the accordion functionality for the Footer, or should I use the accordion as a base, and just change its desgin for Desktop?

**Comment by przspa** [comment]
@Flyingmana https://storybook.storefrontui.io/?path=/story/organisms-tabs--basic check SfTabs I think this component can be helpful

**Comment by Flyingmana** [comment]
mobile design is now also in 
image

Probably needs a bit of fine tuning, could not find the opened state in the figma designs.

I think it needs to be moved to Organisms?
Also I would need to know where to find assets to use for the social icons example.

**Comment by przspa** [comment]
@Flyingmana you can export assets from design (https://help.figma.com/article/204-getting-started-with-exports)

**Comment by filrak** [comment]
how about using <SfMenuItem> instead of ColumnElement? It looks exactly the same and serves same purpose. Also we can include much more things than just list in footer column so it seems like a right choice

**Comment by filrak** [comment]
@Flyingmana any updates here?

**Comment by filrak** [comment]
@Flyingmana we will finish this PR by ourselves ;)

**Comment by Flyingmana** [comment]
ahh yeah, sorry for the inconvenience, I have some very busy weeks currently

**Comment by filrak** [comment]
No problem at att! ;)

**Pull request closed without merging**
