### PR TITLE
#657 moving to css vars

### PR DESCRIPTION
**Pull request by ClaudiaPascualGea**
# Related issue
https://github.com/DivanteLtd/storefront-ui/issues/657

# Scope of work

Components scss files are classified within folders following the atomic design principles, each one of them replaces SCSS variables with CSS properties decreasing the number of mixins to deal with.
Moreover, taking advantage of CSS properties for some components reduces the abuse of !important properties for color variants, check the example below:

```
--circle-icon-color: var(--c-on-primary);
--circle-icon-hover-background: var(--c-primary-lighten);
```

Enforcing the mobile-first with min-width makes the mobile style the default one. Following media queries target progressively larger screens and they work better than using max-width where implicitly the design is desktop-first.

A couple of utility color functions for color-variants generation have been added as well, they work through mixins including CSS properties.

# Checklist

- [X] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [X] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by ClaudiaPascualGea** [comment]
The branch is based on your latest master, let me know if I have to update it with your develop in this WIP phase.

**Comment by pspaczek** [comment]
@ClaudiaPascualGea it looks awesome 🚀 

I have a few small things: 
A. We base on the develop branch and you should start on it because is the most recent branch 
B. You have enabled some linter for SCSS (you use 4 tab and we use 2 tab). I will add stylelint for scss
C. Please check #609 beacuse @mayashavin working on changes in typography and color. We should back from hsl to hex css.

Now I just look for your PR and I love you work 💚 What is your next step? Do you want to add some improvements or just polish your PR?

**Comment by pspaczek** [comment]
@ClaudiaPascualGea maybe you want to add the second improvement to your PR and limit number of SCSS vars in components #445?

**Comment by ClaudiaPascualGea** [comment]
Hi @pspaczek 😄 

I have included the following changes:

- I have updated the PR with develop branch.
- I have also fixed the issue with the 2 tabs

I will take a look now at the issues you told me ([#609](https://github.com/DivanteLtd/storefront-ui/pull/609) and [#445](https://github.com/DivanteLtd/storefront-ui/issues/445)) to check if I can add any further improvement.

Thank you so much 🚀

**Comment by ClaudiaPascualGea** [comment]
Hi 😃 

I have included the colors and icon sizes improvements made in #609.

Thanks!

**Pull request merged**
