### PR TITLE
Remove unnecessary modifiers

### PR DESCRIPTION
**Pull request by dbolufer**
# Related issue
https://github.com/DivanteLtd/storefront-ui/issues/295

# Scope of work
This close https://github.com/DivanteLtd/storefront-ui/issues/295

Remove unnecessary --secondary modifiers from SCSS and update storybook to also remove it

# Screenshots of visual changes
Don't needed

# Checklist

- [X] I followed [composition rules](https://docs.storefrontui.io/component-rules.html) for my component
- [X] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by dbolufer** [comment]
I'm not sure if I understand the purpose of the issue, it is labeled as Medium and if I done it by the right way I think it should be labeled as easy

**Comment by filrak** [comment]
@dbolufer @leomp12 yeah sorry I should've describe it better, hope it wouldn't add you much fo extra work @dbolufer

**Comment by filrak** [comment]
@dbolufer do  you want to finish ti or should I close the PR?

**Comment by dbolufer** [comment]
Hi! We are very bussied do to Black Friday, sorry about our delay.

We are trying to fix it next week

**Comment by filrak** [comment]
Awesome, thank you ;)

**Pull request closed without merging**
