### PR TITLE
[WIP] chore/linter

### PR DESCRIPTION
**Pull request by przspa**
# Related issue

`eslint-plugin-vue` doesnt support our component split stratedy: 
``` html
<!-- component.vue -->
<template src="./template.html"></template>
<style src="./style.scss"></style>
<script src="./index.js"></script>
```
[issue1](https://github.com/vuejs/eslint-plugin-vue/issues/490) [issue2](https://github.com/mysticatea/vue-eslint-parser/issues/28)
# Scope of work

! merge after #470
- [x] just add eslint to `packages/vue` and use `extends: ["plugin:vue/essential", "plugin:vue/strongly-recommended", "plugin:vue/recommended"]` 
- [x] remove prettier, they broaken `Multi-attribute elements` rules :( 

# Screenshots of visual changes

# Checklist

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by przspa** [comment]
I will open this isssue after docs changes

**Comment by goatandsheep** [comment]
how did you fix the vue template issue?

**Comment by pspaczek** [comment]
We can't do that :(  You can't lint html with vue eslin rules :(

**Comment by goatandsheep** [comment]
okay. Thanks anyways!

**Pull request closed without merging**
