### PR TITLE
fix(docs): typos & misleading links 

### LINKED ISSUE #1303: [BUG] Typos + misleading links in Documentation
**Describe the bug**

Some typos in docs to fix:
- [become-a-contributor.md](https://docs.storefrontui.io/contributing/become-a-contributor.html#work-on-documentation) - `extremply` instead of `extremly`
- [coding-guidelines.md](https://docs.storefrontui.io/contributing/coding-guidelines.html#css-custom-properties) `you cand find` instead of `you can find` 
some broken links like `coding-guidelines.md#Unit-tests` instead of lower case `coding-guidelines.md#unit-tests`  and more.

I can handle it by myself.

### PR DESCRIPTION
**Pull request by roiLeo**
# Related issue

Closes #1303 

# Scope of work

Fix Documentation typos and link

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed

If applicable:

- [x] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))
 - [x] I accept [Individual Contributor License Agreement](https://github.com/DivanteLtd/next/blob/master/CLA.md)

### CODE REVIEW

**Comment by daksamit** [comment]
@roiLeo in `coding-guidelines.md` you also fix missing spaces behind brackets (like `.sf-arrow{`) and indentations in code snippets (2 not 4) and missing dot at line 91 (`.sf-button`)

**Comment by filrak** [comment]
Thank you!

**Comment by roiLeo** [comment]
I've added some changes from what @daksamit said.

**Comment by filrak** [comment]
So thank you again, merging!

**Pull request merged**
