### PR TITLE
feat: SfTransition as a functional component

### PR DESCRIPTION
**Pull request by martaradziszewska**
# Related issue

Related #957

# Scope of work

- [x] add SfTransition as a functional component to use amongst the project
- [x] add 'transition' prop to SfBottomModal
- [x] transition prop receives also `false` to turn off the transition
- [x] as a default transition name is 'fade' but this can be discussed more

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))
 - [ ] I accept [Individual Contributor License Agreement](https://github.com/DivanteLtd/next/blob/master/CLA.md)

### CODE REVIEW

**Comment by pspaczek** [comment]
@martaradziszewska good job! :) Can we use https://vue-loader.vuejs.org/guide/functional.html this way to defined functional components?

**Comment by pspaczek** [comment]
maybe we can add stories for this component, wdyt @martaradziszewska

**Comment by martaradziszewska** [comment]
@pspaczek sure, a story sounds good! I agree :) As in vue next template with functional option will be removed we can go with standard component :)

**Comment by pspaczek** [comment]
@Michal-Dziedzinski can you refactor this component to standard component, Vue 3 probably doesn't support functional components

**Comment by martaradziszewska** [comment]
@pspaczek Vue 3 will still support functional components as a simple render function. Option "functional" in template will be removed. But I am still thinking should we consider refactor at all, keeping in this shape will improve performance as this component won't be keep any state etc. WDYT @Michal-Dziedzinski ?

**Comment by Michal-Dziedzinski** [comment]
@martaradziszewska  I agree, in Vue 3 functional components must be written as plain functions and in my opinion it is worth to leave it as a functional component if we have no state

**Pull request merged**
