### PR TITLE
workflow: prepublish script

### PR DESCRIPTION
**Pull request by patzick**
# Scope of work

Prepublish script same as postpublish.

### CODE REVIEW

**Comment by przspa** [comment]
@patzick probable you should copy version.js :) because it runs before publishing a package to npm. You miss ` createVueComponentsDocs();`. When we publish to npm we use a script to do these things but now we do it twice?

**Comment by patzick** [comment]
@pszspa sure, so in version.js we should call prepublish, as for local publish we don't need component docs. If you want we can also just invoke version script. Doesn't have much difference to me, just needed these two steps to be done:)

**Comment by filrak** [comment]
If anything we should just have **only** `version` that runs before publication and `postpublish` that clears after it.

**Comment by patzick** [comment]
@filrak version script asks for the new version number, so it's a potential problem with automation. 
Leaving this up to you, I've done this by doing the same script commands on CI/CD, but shouldn't work that way. I'm still voting for accessible artefact of newest develop to fetch by working projects, would make life easier :)

**Pull request closed without merging**
