### PR TITLE
Feat/#69 CSS  for loading spinners

### PR DESCRIPTION
**Pull request by leomp12**
# Related issue

https://github.com/DivanteLtd/storefront-ui/issues/69

# Scope of work

- CSS classes for bounce and linear loading spinners;
- Stories for spinners (utilities);

### CODE REVIEW

**Comment by filrak** [comment]
Imho it might be agood idea to have a loading states for different types of components that usually consume some data (especially ProductCard and product itself) + we could have a general v-spinner directive that adds a spinner on top of current component - wdyt?

image

**Comment by leomp12** [comment]
Agree, btw we can use skeletons correctly on these components (as in the LinkedIn example).
I just think we can use a `SfSpinner` component instead of using `v-spinner` directive + we can add a `v-spinner` or `v-loading` directive to trigger a spinner and overlay on top of body, specially for route transitions...

**Comment by filrak** [comment]
Agree :) so just a component

**Comment by leomp12** [comment]
Yes, the spinners themselves haven't position absolute because I thought of putting the absolute position in the component's root div.

**Comment by filrak** [comment]
Hey, will you add a SfSpinner component in this PR or only a CSS?

**Comment by leomp12** [comment]
I can add here, in fact I put only the CSS to decide first, and then I just forgot...

**Comment by leomp12** [comment]
@filrak `SfSpinner` component is ready, but I'm not sure where to add the directive, `src/index.js`?

**Comment by filrak** [comment]
Let's leave it with component for now. I started being skeptical about directive since it's hard to customize it. Once we start playing with spinners and feel they're limited and we need directive we can add it - wdyt?

**Comment by filrak** [comment]
Also maybe we can merge utilities and spinner component and just have a type property in there?

**Comment by leomp12** [comment]
I'm not sure if I understand, you're suggesting to remove the spinners from CSS utilities and leave only the component? And add a type property to handle the spinner color?

**Comment by filrak** [comment]
answered in dm ;)

**Comment by leomp12** [comment]
@filrak as discussed, I think we can just close this PR and replace it by SfLoading (with skeleton loading), we're not going to use spinners at all, right?

**Comment by filrak** [comment]
Minor issue but on designs this dots are much smaller and closer to each other ;)
image

**Comment by filrak** [comment]
We will but ahndle this with same component. Thanks!

**Pull request closed without merging**
