### PR TITLE
fix: jest tests console bugs fix

### LINKED ISSUE #1327: [BUG] Injecton "tabConfig" not found in SfTab
**Describe the bug**
There is error: `[Vue warn]: Injection "tabConfig" not found` in SfTab

**How to reproduce**
1. run `test:dev` npm script

**Expected behavior**
Error does not occur

**Actual behavior**
Error is occur

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue
Closes #1327 

# Scope of work
Add silent modification to jest test - turn off the console.error showing.

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [x] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
I added modification to jest test, but I'm not sure if this is good solution to turn off all console messages. Wdyt @justyna @mayashavin

**Review by justyna-13 — COMMENTED** [review]
I don't think it's a good idea :slightly_smiling_face: with all these messages we can easily see if any tests need to be improved or are deprecated. In this particular case, we should just fix SfTab test that can't find injection

**Comment by AdamPawlinski** [comment]
Yes, you are right, so I fixed it and other bugs in console. Please evaluate @justyna-13.

**Review by justyna-13 — APPROVED** [review]
:+1:

**Pull request merged**
