### PR TITLE
[WIP]feat: add webapck confg for sfui support

### PR DESCRIPTION
**Pull request by decadef20**
# Related issue

[Create a mergable webpack build for sfui support](https://github.com/DivanteLtd/storefront-ui/issues/115)

# Scope of work
According to the [issue](https://github.com/DivanteLtd/storefront-ui/issues/115), nuxt app and vue-cli app already support sfc and scss, here we just need to provide the webpack config to  the project which does not support. 

Here is the usage of my design.
```js
// here is user webpack.config.js
const sfuiWebpackConfig = require('/path/to/sfui.webpck.config.js');
const merge = require('webpack-merge')

module.exports =  merge(customConfig, sfuiWebpackConfig)

```

Any pieces of advice will be welcomed. Thanks.

### CODE REVIEW

**Comment by filrak** [comment]
Great job ;)
I think we should ahve it also splitted in presents for every typo of content (.vue, .scss etc) in case someone has part of it in their webpack build. WDYT?

Also could you also propose a documentation for this?

**Comment by decadef20** [comment]
Yead. Put it splited is necessary.
where directory do I put documentation and demo project?

**Comment by filrak** [comment]
I think demo project can be even a separate repo. Regarding docs it's generally a part of installation proces for repos other than nuxt/vue-cli. You can add sth like "Click here to see how to install Storefront UI in other projects" with a link to doc about this webpack config. Please confirm with @lauragift21 as she is taking care of our docs now

**Comment by filrak** [comment]
@decadef20 the docs look great ;)

**Comment by decadef20** [comment]
The next step is to create a repo for the demo. I'll talk with @lauragift21  about the document  in detail.

**Comment by filrak** [comment]
@decadef20 any progress on this?

**Comment by decadef20** [comment]
@filrak  I update doc the create a demo project. There are several questions to be confirmed.
- the path of `sfui.webpack.js` after build
- where to put the demo project，a separated repo or monorepo

**Comment by filrak** [comment]
@decadef20 what you mean by after build?
Example project should be a separate repo I believe and linked as an example

**Comment by decadef20** [comment]
@filrak  which directory should `sfui.webpack.js` file be put in under build mode? 
That's to say, if developers want to import something from `sfui.webpack.js` file, they should know the path of that file.
Do I make it clear?

**Comment by filrak** [comment]
Bud, I must've missed this post, SORRY. Are you still willing to finish this? Imho `@storefront-ui/vue/webpack`

**Comment by decadef20** [comment]
@filrak  I'm always here and waiting for your response.

**Comment by filrak** [comment]
I'd say - Populate @storefront-ui/vue/webpack with sample minimal webpack config and create a doc how to use it in a fresh project with webpack merge.

What do you think? ;)

**Comment by filrak** [comment]
@decadef20 would you like me to finish this? :)

**Comment by decadef20** [comment]
> @decadef20 would you like me to finish this? :)

Ok. Thanks for your working.

**Comment by filrak** [comment]
It's 90% done by you so thanks for yours!

**Pull request closed without merging**
