### PR TITLE
fix: SfCircleIcon in disabled state with color modifier

### LINKED ISSUE #1420: [BUG] SfCircleIcon in disabled state with color modifier
**Describe the bug**
When color modifier is added in disabled state it doesn't look like disabled. 

**How to reproduce**
Go to CircleIcon and add color modifier e.g. color-warning and turn disabled on. See the result.  

**Expected behavior**
No matter what modifier is added it should look like disabled in disabled state. 

**Screenshots**
image

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

### PR DESCRIPTION
**Pull request by ilumin**
# Related issue

Closes #1420 

# Scope of work
Added `:disabled` inside `sf-circle-icon color-#{$color}` and `sf-circle-icon--small color-#{$color}`

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [x] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by justyna-13 — CHANGES_REQUESTED** [review]
Looks good @ilumin! Just a small improvement - when you hover these elements with a disabled state your changes disappear.  We need to add them to the hover too

**Comment by ilumin** [comment]
Roger that.

**Comment by ilumin** [comment]
@justyna-13 It's already applied disabled when hover.
Screen Shot 2020-10-19 at 8 59 19 AM

**Review by justyna-13 — APPROVED** [review]
Great job @ilumin!

**Review by AdamPawlinski — APPROVED** [review]

**Pull request merged**
