### PR TITLE
fix(molecules):  click events is not emitted in SfBanner

### PR DESCRIPTION
**Pull request by aniamusial**
# Related issue
#456 

# Scope of work
Added suggested change for click emit to SfBanner buttons.

# Checklist

- [x] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by filrak** [comment]
[This is just suggestion]
Shouldn't whole banner be clickable, not just a button? @przspa @EduardDopler @mayashavin ?

**Comment by EduardDopler** [comment]
When the banner is <1024px wide there is no button, so at least then the whole banner should be clickable. When there is a button (≥1024px), I would leave it in its current state.

I noticed that the story has a typo: 
```
"CSS Modifiers",
{
  "sf-banner--left": "sf-banner--left",
  "sf-banner--slim": "sf-banner-slim"
},
```
The `slim` value misses a hyphen, that's why the modifier doesn't work in the storybook.

One more thing: When the banner is small (<1024px), the text is always left-aligned. Is this on purpose? Shouldn't it behave like its larger counterpart and be right-aligned until it's modified by `sf-banner--left`? The way it is now, the text is illegible if the background is dark in the left area (like in our shoe image).

**Comment by przspa** [comment]
@filrak but when we have a button then the user wants to use just button. When he clicks the background and it trigger @click then can be confused. But on mobile, he wants to click the banner 😈. Probably it can be a problem when developer want used <RouterLInk/>

**Comment by aniamusial** [comment]
I've added some workaround for te problem - now on desktop only button is clickable, and on mobile the whole banner

**Comment by pspaczek** [comment]
@aniamusial please fix unit test :) check SfFooter and matchMedia.mock :)

**Comment by EduardDopler** [comment]
As this is the first component using `matchMedia` to detect whether this is mobile or desktop, I think it's okay to have `1024` defined in the component's `data`. But at some point maybe we should define it somewhere outside of a specific component (maybe in _shared_?)

And I personally wouldn't create a distinct mock file but implement the mock logic in the .spec file. But that's a matter of taste 👍

**Comment by pspaczek** [comment]
@EduardDopler we have issue for isMobile detection

**Pull request merged**
