### PR TITLE
fix(a11y): access to SfMenuItem by tab key

### LINKED ISSUE #1225: [FEATURE] Add possibility to go through mobile menu by keyboard
**Describe how this feature will help us improve**
Currently, there is not possible to go through mobile menu by keyboard only.

**Describe the solution you'd considered**
By changing `SfMenuItem` and back arrow to `buttons` we can achieve this goal.

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue
Closes #1225 

# Scope of work
Button role added to SfMenuItem with focus directive. Using it by keyboard need to add enter and space event handlers.  

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed

### CODE REVIEW

**Comment by pspaczek** [comment]
@AdamPawlinski what do you think about SfLink here :)?

**Comment by AdamPawlinski** [comment]
I removed role button in menuItem and add sfLink, but I wonder if it's okay according to semantics.

**Comment by pspaczek** [comment]
@AdamPawlinski I resolved our problem, if you use a link then you can use it as SfLink. When it's empty then it's SfButton XD

**Comment by AdamPawlinski** [comment]
Great solution :) Thx @pspaczek

**Pull request merged**
