### PR TITLE
Add Components Docs

### PR DESCRIPTION
**Pull request by EduardDopler**
# Related issue
#420 [Docs] Create missing component docs

## Components
- Bullets
- Checkbox
- Chevron
- Divider
- Heading
- Input
- Loader

### CODE REVIEW

**Comment by filrak** [comment]
@EduardDopler can you please also make this example components work (so checkbox is checked on click etc). Basically the code from example should become an example component

**Comment by EduardDopler** [comment]
> can you please also make this example components work (so checkbox is checked on click etc).

Is this possible though? I mean, the component definitions are all in _enhanceApp.js_ and they have no real state, do they?

**Comment by filrak** [comment]
It iwz you just need to create an instance like I did for SfPagination in Customization doc

**Comment by EduardDopler** [comment]
Wow, didn't know about that feature yet, it's great. I added stateful components where appropriate (Bullets, Checkbox and Loader).

**Comment by filrak** [comment]
Thank you!

**Pull request merged**
